package com.muzi.lovingd.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.muzi.lovingd.item.SaveCalendarItem;

import com.muzi.lovingd.dao.SaveCalendarItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig saveCalendarItemDaoConfig;

    private final SaveCalendarItemDao saveCalendarItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        saveCalendarItemDaoConfig = daoConfigMap.get(SaveCalendarItemDao.class).clone();
        saveCalendarItemDaoConfig.initIdentityScope(type);

        saveCalendarItemDao = new SaveCalendarItemDao(saveCalendarItemDaoConfig, this);

        registerDao(SaveCalendarItem.class, saveCalendarItemDao);
    }
    
    public void clear() {
        saveCalendarItemDaoConfig.getIdentityScope().clear();
    }

    public SaveCalendarItemDao getSaveCalendarItemDao() {
        return saveCalendarItemDao;
    }

}
