package com.muzi.lovingd.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.muzi.lovingd.item.SaveCalendarItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SAVE_CALENDAR_ITEM".
*/
public class SaveCalendarItemDao extends AbstractDao<SaveCalendarItem, Long> {

    public static final String TABLENAME = "SAVE_CALENDAR_ITEM";

    /**
     * Properties of entity SaveCalendarItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property YearTime = new Property(2, String.class, "yearTime", false, "YEAR_TIME");
        public final static Property MinTime = new Property(3, String.class, "minTime", false, "MIN_TIME");
    };


    public SaveCalendarItemDao(DaoConfig config) {
        super(config);
    }
    
    public SaveCalendarItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SAVE_CALENDAR_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"YEAR_TIME\" TEXT," + // 2: yearTime
                "\"MIN_TIME\" TEXT);"); // 3: minTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SAVE_CALENDAR_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SaveCalendarItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String yearTime = entity.getYearTime();
        if (yearTime != null) {
            stmt.bindString(3, yearTime);
        }
 
        String minTime = entity.getMinTime();
        if (minTime != null) {
            stmt.bindString(4, minTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SaveCalendarItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String yearTime = entity.getYearTime();
        if (yearTime != null) {
            stmt.bindString(3, yearTime);
        }
 
        String minTime = entity.getMinTime();
        if (minTime != null) {
            stmt.bindString(4, minTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SaveCalendarItem readEntity(Cursor cursor, int offset) {
        SaveCalendarItem entity = new SaveCalendarItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // yearTime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // minTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SaveCalendarItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setYearTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMinTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SaveCalendarItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SaveCalendarItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
